name: Lint

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "16"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run ESLint
              run: npm run lint

    typescript:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "16"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: TypeScript Check
              run: npm run typecheck
